// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var CivGen = require("../util/CivGen.bs.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Core = require("@material-ui/core");

function Civs(Props) {
  var playerNames = Props.playerNames;
  var players = CivGen.genPlayers(playerNames);
  return React.createElement(Core.Grid, {
              children: null
            }, React.createElement("h3", undefined, "Output"), Belt_Array.map(Belt_List.toArray(players), (function (player) {
                    return React.createElement(Core.Card, {
                                children: React.createElement(Core.CardContent, {
                                      children: null
                                    }, React.createElement("h4", undefined, player.name), Belt_Array.map(Belt_List.toArray(player.civs), (function (civ) {
                                            return React.createElement(Core.Accordion, {
                                                        children: null,
                                                        key: civ.name
                                                      }, React.createElement(Core.AccordionSummary, {
                                                            children: null
                                                          }, React.createElement(Core.Typography, {
                                                                children: civ.leaderName.replace("Leader: ", ""),
                                                                style: {
                                                                  flexBasis: "33.33%",
                                                                  flexShrink: "0"
                                                                }
                                                              }), React.createElement(Core.Typography, {
                                                                children: civ.name
                                                              })), React.createElement(Core.AccordionDetails, {
                                                            children: React.createElement(Core.Typography, {
                                                                  children: civ.detail
                                                                })
                                                          }));
                                          }))),
                                key: player.name
                              });
                  })));
}

var make = Civs;

exports.make = make;
/* react Not a pure module */
