// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var MaterialUi_Grid = require("@jsiebern/bs-material-ui/src/MaterialUi_Grid.bs.js");
var Core = require("@material-ui/core");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.bs.js");
var MaterialUi_TextField = require("@jsiebern/bs-material-ui/src/MaterialUi_TextField.bs.js");

function Setup(Props) {
  var playerNames = Props.playerNames;
  var setPlayerNames = Props.setPlayerNames;
  var match = React.useState(function () {
        return "";
      });
  var setNewPlayerName = match[1];
  var newPlayerName = match[0];
  var onClick = function (evt) {
    evt.preventDefault();
    Curry._1(setPlayerNames, (function (prev) {
            return {
                    hd: newPlayerName,
                    tl: prev
                  };
          }));
    return Curry._1(setNewPlayerName, (function (_prev) {
                  return "";
                }));
  };
  var generateCivs = function (evt) {
    evt.preventDefault();
    return ReasonReactRouter.push("/output");
  };
  var onChange = function (evt) {
    evt.preventDefault();
    var value = evt.target.value;
    return Curry._1(setNewPlayerName, (function (_prev) {
                  return value;
                }));
  };
  return React.createElement(Core.Grid, {
              alignItems: "center",
              children: null,
              container: true,
              spacing: 3
            }, React.createElement(Core.Grid, {
                  children: React.createElement("h2", undefined, "Setup"),
                  item: true,
                  xs: MaterialUi_Grid.Xs._12
                }), React.createElement(Core.Grid, {
                  children: React.createElement(Core.TextField, {
                        fullWidth: true,
                        id: "outlined-basic",
                        label: "Player Name",
                        onChange: onChange,
                        value: MaterialUi_TextField.Value.string(newPlayerName),
                        variant: "outlined"
                      }),
                  item: true,
                  xs: MaterialUi_Grid.Xs._10
                }), React.createElement(Core.Grid, {
                  children: React.createElement(Core.Button, {
                        onClick: onClick,
                        children: "Add Player",
                        fullWidth: true
                      }),
                  item: true,
                  xs: MaterialUi_Grid.Xs._2
                }), React.createElement(Core.Grid, {
                  children: React.createElement(Core.Button, {
                        onClick: generateCivs,
                        children: "Generate Civs",
                        color: "primary",
                        variant: "contained"
                      }),
                  item: true,
                  xs: MaterialUi_Grid.Xs._12
                }), React.createElement(Core.Grid, {
                  children: null,
                  item: true,
                  xs: MaterialUi_Grid.Xs._12,
                  style: {
                    paddingTop: "50px"
                  }
                }, React.createElement("h4", undefined, "Player List"), Belt_Array.map(Belt_List.toArray(playerNames), (function (playerName) {
                        return React.createElement("div", {
                                    key: playerName
                                  }, playerName);
                      }))));
}

var make = Setup;

exports.make = make;
/* react Not a pure module */
